export const INITIAL_DATA_LAYER_OBJECT_BANK = {
  event: '',
  actionGroup: 'interactions',
  eventAction: '',
  eventCategory: '',
  eventLabel: '',
  buttonLocation: null,
  formOrderId: null,
  regionId: null,
  bannerName: null,
  bannerId: null,
  prCat: 'net_kategorii',
  productName: 'net_produkta',
  productId: 'nan',
  cityApplication: null,
  deliveryType: null,
  eventContent: null,
  eventContext: null,
  eventValue: null,
  grclientId: null,
  userAuth: '0',
  formId: null,
  maccountType: null,
  numberType: null,
  accountType: null,
  touchPoint: 'web',
  fa: null,
  intId: null,
  grId: null,
  il: 'anonymous',
  userId: null,
  ecommerce: null,
  timeStamp: Date.now(),
  screenName: 'window.location.pathname',
  region: 'window.localStorage.getItem("region")',
  ref: 'window.document.referrer',
  ph: null,
  em: null,
}

export const INITIAL_DATA_LAYER_OBJECT_DENGI = {
  event: '',
  actionGroup: 'interactions',
  eventAction: '',
  eventCategory: '',
  eventLabel: '',
  buttonLocation: null,
  formOrderId: null,
  regionId: null,
  bannerName: null,
  bannerId: null,
  prCat: 'net_kategorii',
  productName: 'net_produkta',
  productId: 'nan',
  cityApplication: null,
  deliveryType: null,
  eventContent: null,
  eventContext: null,
  eventValue: null,
  grclientId: null,
  userAuth: '0',
  formId: null,
  maccountType: null,
  numberType: null,
  accountType: null,
  touchPoint: 'web',
  fa: null,
  intId: null,
  grId: null,
  il: 'anonymous',
  userId: null,
  ecommerce: null,
  timeStamp: Date.now(),
  screenName: 'window.location.pathname',
  region: 'window.localStorage.getItem("region")',
  ref: 'window.document.referrer',
  ph: null,
  em: null,
}

export const DYNAMIC_PARAMETERS: Array<keyof typeof INITIAL_DATA_LAYER_OBJECT_BANK> = ['ref', 'region', 'screenName', 'timeStamp']
export const ADDITIONAL_REMOVE_COLUMNS = ["{object}", "screenshot 23"] // TODO вывести в интерфейс
export const INFO_COLUMNS = ["№ События", "screenshot 1", "Event description", "коммент", "screenshot 2"].concat(ADDITIONAL_REMOVE_COLUMNS) // Вывести в интерфейс
export const URL_REGEX = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)/